/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apress_movieplayer_AviPlayer */

#ifndef _Included_com_apress_movieplayer_AviPlayer
#define _Included_com_apress_movieplayer_AviPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apress_movieplayer_AviPlayer
 * Method:    render
 * Signature: (Landroid/view/SurfaceHolder;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_apress_movieplayer_AviPlayer_render
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
